name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    name: Check Lint and Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Checks
        run: turbo run checks

  test-unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Run Unit Tests
        run: turbo run test:unit

  test-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Run E2E Tests
        run: turbo run test:e2e

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: Playwright Report
          path: playwright-report/
          retention-days: 30
